#!/bin/bash

#############################################################
#############################################################
###       Maxime Ulysse Garcia, max@ithake.eu, 2013       ###
###                                                       ###
###          Questions and suggestions WELCOMED!          ###
###                                                       ###
###       This thesis template largely derives from       ###
###            Charles Chapple, Robert Castelo            ###
###          Sergio Mendoza and Sergi Castellano          ###
###             Under GNU/GPL copyleft license            ###
###                                                       ###
###         FEEL FREE TO USE IT AND IMPROVE IT!!!         ###
#############################################################
#############################################################

#use : ./UpdateBibliography

#If you use Mendeley, if you sync everything in one file, it should be library.bib
#If you use 1 file per collection or 1 file per document, just cat the collection/documents you're interested in, or everything...
#In my case, ../../Biblio/ is where my bibTeX files are compared to this document.

cat ../Biblio/*.bib |
grep -v 'Automatically generated by Mendeley' |
grep -v 'Any changes to this file will be lost if it is regenerated' |
grep -v 'shorttitle = {' |
grep -v 'mendeley-tags = {' |
grep -v 'institution = {' |
grep -v 'publisher = {' |
grep -v 'pages = {' |
grep -v 'month = ' |
grep -v 'doi = {' |
grep -v 'pmid = {' |
grep -v 'url = {' |
grep -v 'file = {' |
grep -v 'abstract = {' |
grep -v 'keywords = {' |
grep -v 'isbn = {' |
grep -v 'issn = {' |
grep -v 'editor = {' |
grep -v 'address = {' |
grep -v 'From Duplicate' |
grep -v '^s*$' |
grep -v 'annote = {' > bibliography/biblio.bib

sed -i 's/\\o /\{\\o\}/g' bibliography/biblio.bib
sed -i 's/^\},//g' bibliography/biblio.bib
sed -i 's/^\r//g' bibliography/biblio.bib
sed -i 's/^\\{:\\}//g' bibliography/biblio.bib